### ISSUE TITLE
Please release a new builder

### ISSUE THREAD

**Issue by ajdergute** [paketo-buildpacks/builder-jammy-base#441]
In order to be able to use latest lifecycle v0.19 a new builder is required. When do you plan a release?

Context: ATM it is impossible to build against platform APi v0.13.

**Comment by ajdergute** [comment]
No news on this?

**Comment by pacostas** [comment]
@ajdergute I see a release here https://github.com/paketo-buildpacks/builder-jammy-base/releases/tag/v0.4.280 . Does this work?

**Comment by ajdergute** [comment]
Oh missed that. Yes this works.
